#v2
name: Build Thymio Suite for Windows

on:
  push:
    branches:
      - launcher-font-macos-fix
    tags:
      - "2.*"
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup vcpkg and install dependencies
        run: |
          git clone https://github.com/Mobsya/vcpkg.git C:\vcpkg
          cd C:\vcpkg
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe install openssl zlib boost-program-options boost-filesystem boost-asio boost-date-time boost-thread

      - name: Configure project with CMake
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DCREATE_QT_CONF_FILE=ON

      - name: Build project
        run: |
          cd build
          cmake --build . --config Release -- /maxcpucount

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure --build-config Release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ThymioSuite
          path: build\ThymioSuite-*.exe
